### PR TITLE
Make singleton shared states static

### PR DESCRIPTION
**Pull request by Cvolton**
Among-Us-Red-Crewmate

### CODE REVIEW

**Review by Cvolton — COMMENTED** [review]
theyre good changes i rate 10/10

**Review by FigmentBoy — COMMENTED** [review]
amogus

**Comment by CdcOnGitHub** [comment]
i am sure that you are sus acvoltonus

**Comment by CdcOnGitHub** [comment]
sustonus

**Comment by CdcOnGitHub** [comment]
`c`

**Pull request merged**
