### PR TITLE
add more known addresses for windows

### PR DESCRIPTION
**Pull request by spookybear0**
these have NOT been tested in geode yet but I am fairly certain that they are correct

### CODE REVIEW

**Comment by HJfod** [comment]
https://www.youtube.com/watch?v=rR4n-0KYeKQ

**Comment by spookybear0** [comment]
Thank you for merging!

**Comment by HJfod** [comment]
👍

**Comment by spookybear0** [comment]
oh shit, can you fix it on this repo, i already deleted the fork

**Comment by HJfod** [comment]
yea

**Pull request merged**
